config/urls.py
from django.contrib import admin
from django.urls import path
from music import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.main, name='main'),

    # admin
    path('admin/main', views.adminMain, name='admin_main'),
    path('admin/agency/', views.adminAgency, name='admin_agency'),
    path('admin/artist/', views.adminAritst, name='admin_artist'),
    path('admin/album/', views.adminAlbum, name='admin_album'),
    path('admin/album/<int:album_id>/song/', views.adminSong, name='admin_song'),
    path('admin/album/review/', views.adminAlbumReview, name='admin_album_review'),
    path('admin/song/review/', views.adminSongReview, name='admin_song_review'),
    path('admin/album/<int:album_id>/delete', views.adminAlbumDelete, name='admin_album_delete'),
    path('admin/song/<int:song_id>/delete', views.adminSongDelete, name='admin_song_delete'),
    path('admin/album/review/<int:review_id>/delete/', views.adminAlbumReviewDelete, name='admin_album_review_delete'),
    path('admin/song/review/<int:review_id>/delete/', views.adminSongReviewDelete, name='admin_song_review_delete'),
    path('admin/', admin.site.urls),

    # User
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # Album
    path('album/<int:album_id>/', views.albumDetail, name='album'),
    path('album/<int:album_id>/review/', views.albumReview, name='albumReview'),
    path('album/<int:album_id>/review/create/', views.albumReviewCreate, name='albumReview_create'),
    path('album/review/<int:review_id>/', views.albumReviewModify, name='albumReview_modify'),
    path('song/<int:song_id>/review/', views.songReview, name='songReview'),
    path('song/<int:song_id>/review/create/', views.songReviewCreate, name='songReview_create'),
    path('song/review/<int:review_id>/', views.songReviewModify, name='songReview_modify'),

    # Artist
    path('artist/<int:artist_id>', views.artistDetail, name='artist')

]

music/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    _id = models.CharField(db_column='_id', primary_key=True, max_length=12)
    password = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'user'


class Agency(models.Model):
    agencyName = models.CharField(db_column='agencyName', primary_key=True, max_length=30)

    class Meta:
        managed = False
        db_table = 'Agency'


class Artist(models.Model):
    id = models.IntegerField(auto_created=True)
    agencyName = models.OneToOneField(Agency, models.DO_NOTHING, db_column='agencyName')
    artistName = models.CharField(db_column='artistName', max_length=30, primary_key=True)  # Field name made lowercase.
    isSolo = models.IntegerField(db_column='isSolo', blank=True, null=True)  # Field name made lowercase.
    debutedAt = models.DateTimeField(db_column='debutedAt', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Artist'
        unique_together = (('agencyName', 'artistName'),)


class Member(models.Model):
    id = models.IntegerField(auto_created=True, primary_key=True)
    agencyName = models.ForeignKey(Agency, models.DO_NOTHING, db_column='agencyName', related_name='Agency_agencyName')
    artistName = models.ForeignKey(Artist, models.DO_NOTHING, db_column='artistName')
    memberName = models.CharField(db_column='memberName', max_length=30)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Member'
        unique_together = (('artistName', 'memberName'),)


class Album(models.Model):
    albumId = models.IntegerField(db_column='albumId', primary_key=True)  # Field name made lowercase.
    albumName = models.CharField(db_column='albumName', max_length=30)  # Field name made lowercase.
    artistName = models.CharField(db_column='artistName', max_length=30)  # Field name made lowercase.
    agencyName = models.ForeignKey(Agency, models.DO_NOTHING, db_column='agencyName')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Album'


class Category(models.Model):
    categoryId = models.IntegerField(db_column='categoryId', primary_key=True)  # Field name made lowercase.
    category = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Category'


class AlbumCategory(models.Model):
    id = models.IntegerField(auto_created=True, primary_key=True)
    albumId = models.ForeignKey(Album, models.DO_NOTHING, db_column='albumId')  # Field name made lowercase.
    categoryId = models.ForeignKey('Category', models.DO_NOTHING, db_column='categoryId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'AlbumCategory'
        unique_together = (('albumId', 'categoryId'),)


class Composer(models.Model):
    composerId = models.IntegerField(db_column='composerId', primary_key=True)  # Field name made lowercase.
    composerName = models.CharField(db_column='composerName', max_length=30, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'composer'


class Lyricist(models.Model):
    lyricistId = models.IntegerField(db_column='lyricistId', primary_key=True)  # Field name made lowercase.
    lyricistName = models.CharField(db_column='lyricistName', max_length=30, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Lyricist'


class Song(models.Model):
    id = models.IntegerField(auto_created=True)
    albumId = models.ForeignKey(Album, models.DO_NOTHING, db_column='albumId')  # Field name made lowercase.
    songName = models.CharField(db_column='songName', max_length=30, primary_key=True)  # Field name made lowercase.
    categoryId = models.ForeignKey(Category, models.DO_NOTHING, db_column='categoryId')  # Field name made lowercase.
    lyrics = models.TextField(blank=True, null=True)
    createdAt = models.DateTimeField(db_column='createdAt', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Song'
        unique_together = (('albumId', 'songName', 'categoryId'),)


class SongComposer(models.Model):
    id = models.IntegerField(auto_created=True, primary_key=True)
    albumId = models.ForeignKey(Album, models.DO_NOTHING, db_column='albumId', related_name="+")
    songName = models.ForeignKey(Song, models.DO_NOTHING, db_column='songName', to_field='songName')
    composerId = models.ForeignKey(Composer, models.DO_NOTHING, db_column='composerId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'songComposer'
        unique_together = (('albumId', 'songName', 'composerId'),)


class SongLyricist(models.Model):
    id = models.IntegerField(auto_created=True, primary_key=True)
    albumId = models.ForeignKey(Album, models.DO_NOTHING, db_column='albumId', related_name="+")
    songName = models.ForeignKey(Song, models.DO_NOTHING, db_column='songName', to_field='songName')
    lyricistId = models.ForeignKey(Lyricist, models.DO_NOTHING, db_column='LyricistId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'songLyricist'
        unique_together = (('albumId', 'songName', 'lyricistId'),)


class SongReview(models.Model):
    id = models.IntegerField(auto_created=True, primary_key=True)
    userId = models.ForeignKey('User', models.DO_NOTHING, db_column='userId')  # Field name made lowercase.
    albumId = models.ForeignKey(Album, models.DO_NOTHING, db_column='albumId', related_name="+")
    songName = models.ForeignKey(Song, models.DO_NOTHING, db_column='songName')
    star = models.IntegerField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'songReview'
        unique_together = (('userId', 'albumId', 'songName'),)


class AlbumReview(models.Model):
    id = models.IntegerField(auto_created=True, primary_key=True)
    userId = models.ForeignKey('User', models.DO_NOTHING, db_column='userId')  # Field name made lowercase.
    albumId = models.ForeignKey(Album, models.DO_NOTHING, db_column='albumId')  # Field name made lowercase.
    star = models.IntegerField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'AlbumReview'
        unique_together = (('userId', 'albumId'),)

templates/albumDetail.html
{% extends "base.html" %}
{% load filter %}
{% block content %}
<div class="container my-3">
    <div class="box border px-4 rounded">
         <div class="my-3 " style="height: auto !important;">
            <h2 class="pb-3 mb-0 font-weight-bold">{{ album.albumName }}</h2>
            <h4><a class="text-decoration-none " style="color:mediumseagreen;" href="{% url 'artist' artist.id %}">{{ artist.artistName }}</a></h4>
        </div>
        <div class="d-flex justify-content-between">
            <div class="my-1">
                <p>
                    <strong>발매일</strong>:
                    {% for song in album.song_set.all|slice:":1" %}
                        {{ song.createdAt| date:"Y-m-d" }}
                    {% endfor %}
                </p>
                <p>
                    <strong>장르</strong>:
                    {% for cate in album.albumcategory_set.all %}
                        {{ cate.categoryId.category }}
                        {% if forloop.last == False %}
                            ,
                        {% endif %}
                    {% endfor %}
                </p>
                <p>
                    <strong>기획사</strong>:
                    {{ artist.agencyName.agencyName }}
                </p>
            </div>
            <div class="my-1">
                <p>
                    <i class="fa-solid fa-star"></i> &nbsp; {{ star }}
                </p>
                <p>
                    리뷰&nbsp;<a href="{% url 'albumReview' album.albumId %}" style="color: lightseagreen;"> {{ album.albumreview_set.count }} 개</a> >
                </p>
            </div>
        </div>
    </div>
    <div class="song-block my-3">
    {% for song in song_list %}
        <div class="music-item p-3 my-3 border rounded">
            <div class="flex-grow-1 px-2">
                <span class="badge bg-secondary">Track #{{ forloop.counter }}</span>
                <h3>{{ song.songName }}</h3>
            </div>
            <div class="d-flex justify-content-end my-1">
                <p class="px-3">
                    <i class="fa-solid fa-star"></i> &nbsp; {{ stars|index:forloop.counter0 }}
                </p>
                <p>
                    리뷰&nbsp;<a href="{% url 'songReview' song.id %}" style="color: lightseagreen;"> {{ song.songreview_set.count }} 개</a> >
                </p>
            </div>
            <div class="d-flex justify-content-end my-0 py-0">
                <div class="px-2"><strong>장르</strong> : {{ song.categoryId.category }}</div>
                <div class="px-2">
                    <strong>발매일</strong> : {{ song.createdAt|date:"Y-m-d" }}
                </div>
            </div>
            <div class="p-2 text-break">
                <h5 class="border-bottom border-dark py-2">가사</h5>
                <p style="white-space: pre-line;">{{ song.lyrics }}</p>
            </div>
            <h5>작곡</h5>
            <div class="d-flex justify-content-start border-top border-secondary my-1 py-2">
                {% for composer in song.songcomposer_set.all %}
                    {{ composer.composerId.composerName }}
                    {% if forloop.last == False %}
                        ,
                    {% endif %}
                {% endfor %}
            </div>
            <h5>작사</h5>
            <div class="d-flex justify-content-start border-top border-secondary my-1 py-2">
                {% for lyricist in song.songlyricist_set.all %}
                    {{ lyricist.lyricistId.lyricistName }}
                    {% if forloop.last == False %}
                        ,
                    {% endif %}
                {% endfor %}
            </div>

        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/albumReview.html
{% extends "base.html" %}
{% load filter %}
{% block content %}
<div class="container my-3">
    <div class="box border px-4 rounded">
         <div class="my-3 " style="height: auto !important;">
            <h2 class="pb-3 mb-0 font-weight-bold">{{ album.albumName }}</h2>
            <h4><a class="text-decoration-none " style="color:mediumseagreen;" href="{% url 'artist' artist.id %}">{{ artist.artistName }}</a></h4>
        </div>
        <div class="d-flex justify-content-between">
            <div class="my-1">
                <p>
                    <strong>발매일</strong>:
                    {% for song in album.song_set.all|slice:":1" %}
                        {{ song.createdAt| date:"Y-m-d" }}
                    {% endfor %}
                </p>
                <p>
                    <strong>장르</strong>:
                    {% for cate in album.albumcategory_set.all %}
                        {{ cate.categoryId.category }}
                        {% if forloop.last == False %}
                            ,
                        {% endif %}
                    {% endfor %}
                </p>
                <p>
                    <strong>기획사</strong>:
                    {{ artist.agencyName.agencyName }}
                </p>
            </div>
            <div class="my-1">
                <p>
                    <i class="fa-solid fa-star"></i> &nbsp; {{ star }}
                </p>
                <p>
                    리뷰&nbsp;<a style="color: lightseagreen;"> {{ album.albumreview_set.count }} 개</a> >
                </p>
            </div>
        </div>
    </div>
    <div class="review-block my-3">
        <!--답변 등록-->
        {% if user.is_authenticated %}
            <form action="{% url 'albumReview_create' album.albumId %}" method="post" class="my-3">
            {%  csrf_token %}
            <!-- 오류표시 -->
            {% if form %}
            {% include "form_errors.html" %}
            {% endif %}
            <div class="mb-1 my-1">
                <div class="d-flex justify-content-end">
                    <label class="align-center py-3 px-2" for="star">
                        <i class="fa-solid fa-star"></i>
                    </label>
                    <div class="py-2">
                        <select class="form-select" name="star" id="star">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                    </div>
                </div>

                <textarea class="form-control" placeholder="리뷰를 입력하시오..."name="content" id="content" rows="3"></textarea>
            </div>
            <input type="submit" value="리뷰등록" class="btn btn-primary">
            </form>
        {% endif %}
        <!--답변-->
        {% if review_list %}
        {% for review in review_list %}
            <div class="answer-item p-3 my-3 border rounded">
                <div class="d-flex justify-content-between">
                    <div>
                        <strong>{{ review.userId|id }}</strong> 님
                        {% if request.user.username == review.userId|id %}
                            <a href="{% url 'albumReview_modify' review.id %}">수정</a>
                        {% endif %}
                    </div>
                    <div class="px-3">
                        <i class="fa-solid fa-star"></i> &nbsp; {{ review.star }}
                    </div>
                </div>

                <div class="p-2">{{ review.content }}</div>
            </div>
        {% endfor %}
        <!--답변 페이징 처리 시작-->
        <ul class="pagination justify-content-center">
            {% if review_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ review_list.previous_page_number }}" href="javascript:void(0)">이전</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
            {% endif %}
            {% for page_number in review_list.paginator.page_range %}
                {% if page_number >= review_list.number|add:-5 and page_number <= review_list.number|add:5 %}
                {% if page_number == review_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                {% endif %}
                {% endif %}
            {% endfor %}
            {% if review_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ review_list.next_page_number }}" href="javascript:void(0)">다음</a>
            </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
                </li>
            {% endif %}
        </ul>
        <!--답변 페이징 처리 끝 -->
        {% endif %}
        <form id="searchForm" method="get" action="{% url 'albumReview' album.albumId %}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
    </div>
</div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        const page_elements = document.getElementsByClassName("page-link");
            Array.from(page_elements).forEach(function(element) {
                element.addEventListener('click', function() {
                    document.getElementById('page').value = this.dataset.page;
                    document.getElementById('searchForm').submit();
                });
            });
    </script>
{% endblock %}

templates/artistDetail.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <!--Table-->
    <div class="border-bottom border-secondary py-3" style="text-align: center;">
        <h2>아티스트 정보</h2>
    </div>
    <div class="box border px-4 my-2 rounded">
         <div class="my-3 " style="height: auto !important;">
            <h2 class="pb-3 mb-0 font-weight-bold">{{ artist.artistName }}</h2>
        </div>
        <div class="d-flex justify-content-between pb-2">
            <div>
                <strong>데뷔일</strong> {{ artist.debutedAt|date:"Y-m-d" }}
            </div>
            <div>
                <strong>활동유형</strong>
                {% if artist.isSolo %}
                    솔로
                {% else %}
                    그룹:
                    {% for member in member_list %}
                        {{ member.memberName }}
                        {% if not forloop.last %}
                            ,
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
            <div>
                <strong>기획사</strong>:
                {{ artist.agencyName.agencyName }}
            </div>
        </div>
    </div>
    <div class="border-bottom border-secondary py-1 my-2">
        <h3>전체 앨범</h3>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>앨범 번호</th>
            <th>앨범 이름</th>
            <th>장르</th>
            <th>소속사</th>
            <th>아티스트</th>
            <th>발매일</th>
            <th>리뷰</th>
        </tr>
        </thead>
        <tbody>
        {% if album_list %}
        {% for album in album_list %}
            <tr class="text-center">
                <td class="align-middle">{{ album.albumId }}</td>
                <td>
                    <a class="text-black text-decoration-none" href="{% url 'album' album.albumId %}">
                        {{ album.albumName }}
                    </a>
                </td>
                <td>
                    {% for cate in album.albumcategory_set.all %}
                        {{ cate.categoryId.category }}
                        {% if forloop.last == False %}
                            ,
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{ album.agencyName.agencyName }}</td>
                <td>{{ album.artistName }}</td>
                <td>
                    {% for song in album.song_set.all|slice:":1" %}
                        {{ song.createdAt|date:"Y-m-d" }}
                    {% endfor %}
                </td>
                <td>{{ album.albumreview_set.count }}</td>
            </tr>
        {%  endfor %}
        {%  else %}
            <tr>
                <td colspan="7" style="text-align: center;">앨범이 없습니다.</td>
            </tr>
        {%  endif %}
        </tbody>
    </table>
    <!--Paging-->
    <ul class="pagination justify-content-center">
        {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" data-page="{{ album_list.previous_page_number }}" href="javascript:void(0)">이전</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
        {% endif %}
        {% for page_number in album_list.paginator.page_range %}
            {% if page_number >= album_list.number|add:-5 and page_number <= album_list.number|add:5 %}
            {% if page_number == album_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                </li>
            {% endif %}
            {% endif %}
        {% endfor %}
        {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ album_list.next_page_number }}" href="javascript:void(0)">{{ page_number }}다음</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
            </li>
        {% endif %}
    </ul>
    <!--form-->
     <form id="searchForm" method="get" action="{% url 'main' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="sort" name="sort" value="{{ sort }}">
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Search</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/c7dc2c74ff.js" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류 출력-->
{% if form.errors %}
    <div class="alert alert-danger" style="align-content:center;">
        {% for field in form %}
            <!--필드 오류-->
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!--넌필드 오류-->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-3" style="height: auto !important;">
        <div class="border-bottom border-secondary py-3" style="text-align: center;">
            <h2>Music Search DB</h2>
        </div>
        <!-- Search -->
        <div class="row my-3">
            <div class="col-6">
                <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                    <input type="radio" class="btn-check" name="btnradio" id="btnradio1" value="recent" checked>
                    <label class="btn btn-outline-secondary" for="btnradio1">
                       <i class="fas fa-list"></i>
                    </label>
                </div>
            </div>
            <div class="col-6">
                <div class="input-group">
                    <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                    </div>
                </div>
            </div>
        </div>
        <!--Table-->
        <table class="table">
            <thead>
            <tr class="text-center table-dark">
                <th>앨범 번호</th>
                <th>앨범 이름</th>
                <th>장르</th>
                <th>소속사</th>
                <th>아티스트</th>
                <th>발매일</th>
                <th>리뷰</th>
            </tr>
            </thead>
            <tbody>
            {% if album_list %}
            {% for album in album_list %}
                <tr class="text-center">
                    <td class="align-middle">{{ album.albumId }}</td>
                    <td>
                        <a class="text-black text-decoration-none" href="{% url 'album' album.albumId %}">
                            {{ album.albumName }}
                        </a>
                    </td>
                    <td>
                        {% for cate in album.albumcategory_set.all %}
                            {{ cate.categoryId.category }}
                            {% if forloop.last == False %}
                                ,
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ album.agencyName.agencyName }}</td>
                    <td>{{ album.artistName }}</td>
                    <td>
                        {% for song in album.song_set.all|slice:":1" %}
                            {{ song.createdAt|date:"Y-m-d" }}
                        {% endfor %}
                    </td>
                    <td>{{ album.albumreview_set.count }}</td>
                </tr>
            {%  endfor %}
            {%  else %}
                <tr>
                    <td colspan="7" style="text-align: center;">앨범이 없습니다.</td>
                </tr>
            {%  endif %}
            </tbody>
        </table>
        <!--Paging-->
        <ul class="pagination justify-content-center">
            {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ album_list.previous_page_number }}" href="javascript:void(0)">이전</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
            {% endif %}
            {% for page_number in album_list.paginator.page_range %}
                {% if page_number >= album_list.number|add:-5 and page_number <= album_list.number|add:5 %}
                {% if page_number == album_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                {% endif %}
                {% endif %}
            {% endfor %}
            {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ album_list.next_page_number }}" href="javascript:void(0)">{{ page_number }}다음</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
                </li>
            {% endif %}
        </ul>
        <!--form-->
         <form id="searchForm" method="get" action="{% url 'main' %}">
            <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        const page_elements = document.getElementsByClassName("page-link");
        Array.from(page_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                document.getElementById('page').value = this.dataset.page;
                document.getElementById('searchForm').submit();
            });
        });
        const btn_search = document.getElementById("btn_search");
        btn_search.addEventListener('click', function() {
            document.getElementById('kw').value = document.getElementById('search_kw').value;
            document.getElementById('page').value = 1;
            document.getElementById('searchForm').submit();
        });
    </script>
{% endblock %}